remote_theme             : "mmistakes/minimal-mistakes@4.23.0"
minimal_mistakes_skin    : "dark"

# Site Settings
locale                   : "en-US"
title                    : "twigglers.github.io"
title_separator          : "-"
url                      : "https://twigglers.github.io"
repository               : "twigglers/twigglers.github.io"

# Site Author
author:
  name             : "Richard Nguyen"
  bio              : "Posting experiences from working in the cloud space."
  location         : "Sydney, AUS"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache
